import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Bell, Megaphone, Trophy, UserRound } from "lucide-react";
import DashboardAppBar from "./DashboardAppBar";
import "./Dashboard.css";
import DashboardExtras from "./DashboardExtras";
const people=["Member 1","Member 2","Member 3","Member 4","Member 5"];
const seed=[{task:"Design Review",member:"Member 1",priority:"High",status:"In Progress",due:"01 Jun 2025"},{task:"Sensor Integration",member:"Member 2",priority:"Medium",status:"In Progress",due:"05 Jun 2025"},{task:"Flight Controller Test",member:"Member 3",priority:"Low",status:"To Do",due:"10 Jun 2025"}];
function Telemetry({side}){const x=side==="left"?["ALT : 120M","SPD : 18.4 M/S","BAT : 76%"]:["GPS : LOCKED","SAT : 12","MODE : STANDBY"];return <aside className={`telemetry telemetry-${side}`}>{x.map(a=><span key={a}>{a}</span>)}</aside>}
function Drone({className}){return <svg className={`hud-drone ${className}`} viewBox="0 0 360 300"><g fill="none" stroke="currentColor" strokeWidth="1.15"><path d="M91 112 41 69m57 41L39 127m219-15 52-43m-46 60 58 5M104 114l55 28 78-4 30-24-37-13-73 12-53-18Z"/><path d="m156 142-3 89 51 26 15-71-23-45m-39 90-36-11-5-66m140-43 17 84 42 15 11-56-34-44"/><path d="m159 140 37-6 35 17-11 35-40 7-24-22Z"/><ellipse cx="40" cy="69" rx="38" ry="6"/><ellipse cx="38" cy="127" rx="38" ry="6"/><ellipse cx="310" cy="69" rx="38" ry="6"/><ellipse cx="322" cy="134" rx="38" ry="6"/></g></svg>}
function Mini({announcement,onOpen}){return <section className="mini-card"><header>{announcement?<Megaphone/>:<Trophy/>}<h2>{announcement?"Announcements":"Competitions"}</h2></header>{announcement?<><p className="new-label"><i/> New</p><p>Competition subsystem is currently working on the design review.</p><small>2h ago</small></>:<><p className="label">Current</p><p>DroneTech 2025</p><p className="label event-label">Event Date</p><p>15 - 18 Aug 2025</p></>}<button onClick={onOpen}>View Details <b>-&gt;</b></button></section>}
export default function Dashboard(){const [tasks,setTasks]=useState(seed),[notice,setNotice]=useState(""),[profileOpen,setProfileOpen]=useState(false);const navigate=useNavigate();const cycle=i=>setTasks(rows=>rows.map((r,n)=>n!==i?r:{...r,status:r.status==="To Do"?"In Progress":r.status==="In Progress"?"Done":"To Do"}));return <div className="reference-dashboard"><DashboardAppBar profileOpen={profileOpen} setProfileOpen={setProfileOpen}/><Telemetry side="left"/><Telemetry side="right"/><Drone className="drone-left"/><Drone className="drone-right"/><div className="circuit circuit-left"/><div className="circuit circuit-right"/><main className="reference-content"><section className="top-grid"><section className="subsystem-card"><h1>Sub system Name</h1><div className="member-grid">{people.map(p=><button className="member-card" key={p} onClick={()=>navigate("/team")}><UserRound/><span>{p}</span></button>)}</div></section><Mini announcement onOpen={()=>document.getElementById("announcements")?.scrollIntoView({behavior:"smooth"})}/><Mini onOpen={()=>setNotice("DroneTech 2025 details opened")}/></section><section className="tasks-card"><h2><Bell/> Ongoing Tasks Overview</h2><div className="task-table"><div className="task-row task-head"><span>Task</span><span>Assigned To</span><span>Priority</span><span>Status</span><span>Due Date</span></div>{tasks.map((t,i)=><div className="task-row" key={t.task}><span>{t.task}</span><span>{t.member}</span><span className="priority"><i/> {t.priority}</span><button className={`status status-${t.status.toLowerCase().replace(" ","-")}`} onClick={()=>cycle(i)}>{t.status}</button><span>{t.due}</span></div>)}</div></section><DashboardExtras/></main>{notice&&<button className="dashboard-toast" onClick={()=>setNotice("")}>{notice}<span>x</span></button>}</div>}